// <auto-generated />
namespace ApiSpark.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class loginUserV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loginUserV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202006170130518_loginUser-V1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
